### ISSUE TITLE
Typo for Leather Armor

### ISSUE THREAD

**Issue by gwa2100** [MurkSec/BavariaTheGame#20]
**Describe the bug**
Leather armor is depicted as Lether.

**To Reproduce**
Code error.

**Expected behavior**
Rename it.

**Screenshots**
N/a

**Desktop (please complete the following information):**
0.1D

**Additional context**
N/a

**Comment by Jiandie1** [comment]
i fixed all the instances of this in my repl, but now I have to make the changes all over again then commit
