### ISSUE TITLE
ending function call in Cave_Enter Function class_world.py

### ISSUE THREAD

**Issue by gwa2100** [MurkSec/BavariaTheGame#43]
**Describe the bug**
A call to ending() function is made.  This function exists in the main py file not in class_world.py

**To Reproduce**
N/a

**Expected behavior**

**Screenshots**
def Cave_Enter(self):
    helper_functions.clear_screen()
    self.game_hud()
    if self.BossKilled == False:
      class_oldgraphic.Print_Img('Cave_Enter')
    else:
      print(" You head back to Bavaria....")
      time.sleep(1)
      **ending()**

**Desktop (please complete the following information):**
V0.15D

**Additional context**

**Comment by redwiz666** [comment]
This was fixed while putting in the loop after death option

https://github.com/MurkSec/BavariaTheGame/commit/4c238497f0b6bcf8f7765b1ed36ba1e9a9a4bd6e
