### ISSUE TITLE
Clear Screen Function does not work on Windows

### ISSUE THREAD

**Issue by gwa2100** [MurkSec/BavariaTheGame#44]
**Describe the bug**
Clear screen function prints characters to screen and does not clear the screen.

We need a new method of clearing the screen that will work across multiple platforms.

**To Reproduce**
Just run the game.

**Expected behavior**
The clear screen should clear the screen and be distro agnostic.

**Screenshots**
**[H[J**
Please enter your nametim
**[H[J**
         Please choice your class

1 = Fighter
2 = Monk
3 = Thief
4 = Mage

1
**[H[J
[H[J**

You choose :
Name: tim
Class: Fighter
Health: 35/35
Evasion: 8   Accuracy: 45
Strength: 8
Weapon: Short Sword  Atk rate: 5
Armor: Cloth Armor  Def rate: 10
Do you want to reroll your Character? y/n

**Desktop (please complete the following information):**
 - OS: Using Windows 10 Pro + Python 3.7
 - Version 0.15D

**Additional context**

**Comment by gwa2100** [comment]
@redwiz666  is working it.

**Comment by Comrob2018** [comment]
commit #45 will help make this possible on all machines.

**Comment by redwiz666** [comment]
correct Comrob2018. Thanks for the update
