### ISSUE TITLE
cannot exit Status screen if you have item

### ISSUE THREAD

**Issue by gwa2100** [MurkSec/BavariaTheGame#47]
**Describe the bug**
Cannot exit the status screen if you have a potion.

**To Reproduce**
Press C on the main screen once you have picked up an item.

**Expected behavior**
Should be able to hit enter and exit the screen

**Screenshots**

**Desktop (please complete the following information):**
- Version 0.15D

**Additional context**
It is likely a need for an else statement.

**Comment by redwiz666** [comment]
Comrob2018 fixed issue in commit
https://github.com/MurkSec/BavariaTheGame/pull/52/commits/4b4335c8c247c0c6ae29efa29aa3230d68d032bd
