### ISSUE TITLE
Screen clearing causes text to go to bottom of screen

### ISSUE THREAD

**Issue by gwa2100** [MurkSec/BavariaTheGame#67]
**Describe the bug**
When screen is cleared, it puts the text at the very bottom.  It feels a bit incorrect.

**To Reproduce**
Just run the game

**Expected behavior**
I would think it would refresh the text to the top of the screen

**Desktop (please complete the following information):**
Windows 10
Python 3.7
V 0.16

**Additional context**

**Comment by gwa2100** [comment]
@redwiz666 can you verify if this is an issue?

**Comment by Comrob2018** [comment]
i updated the clear screen helper function, it should now work properly
